controller:
  image: "harbor.cloudbrg.com/cicd/jenkins/jenkins"
  #tag: "2.289.3-jdk11"
  tag: "latest"
  imagePullSecretName: harbor-cred
  
  # List of plugins to be install during Jenkins controller start
  installPlugins: []
    # - kubernetes:1.29.4
    # - workflow-aggregator:2.6
    # - git:4.7.1
    # - configuration-as-code:1.51

  sidecars:
    configAutoReload:
      # If enabled: true, Jenkins Configuration as Code will be reloaded on-the-fly without a reboot.  If false or not-specified,
      # jcasc changes will cause a reboot and will only be applied at the subsequent start-up.  Auto-reload uses the
      # http://<jenkins_url>/reload-configuration-as-code endpoint to reapply config when changes to the configScripts are detected.
      enabled: true
      image: "harbor.cloudbrg.com/cicd/kiwigrid/k8s-sidecar:1.12.2"
      imagePullPolicy: IfNotPresent

agent:
  enabled: true
  image: "harbor.cloudbrg.com/cicd/jenkins/inbound-agent"
  tag: "4.6-1"

serviceAccount:
  create: false
